config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root to: 'home#index'

  Rails.application.routes.draw do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :movies do
    member do
      get :shows
    end
  end

  resources :shows do
    member do
      get :seats
    end
  end

  resources :bookings, only: [:index, :create, :show] do
    collection do
      get :my_bookings
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :load_movie, except: :index

  def index
    authorize Movie
    @movies = Movie.active
  end

  def shows
    authorize @movie, :shows?
    @shows = @movie.shows.upcoming_shows.includes(:screen)
  end

  private

  def load_movie
    @movie = Movie.find_by(id: params[:id])
    unless @movie
      flash[:error] = I18n.t('movie.not_found')
      redirect_to movies_path
    end
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/index.html.haml
%h1 Movies
%hr
%table.table
  %thead
    %th Name
    %th Duration
    %th Actions
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.name
        %td= "#{movie.duration} minutes"
        %td= link_to "Shows", shows_movie_path(movie)

app/views/movies/shows.html.haml
%h1= "#{@movie.name} Shows"
/ add a datepicker here
%hr
%table.table
  %thead
    %th Show Time
    %th Screen
    %th Status
    %th Book Seat
  %tbody
    - @shows.each do |show|
      %tr
        %td= show.start_time
        %td= show.screen.name
        %td= show.status
        %td= link_to "Book Seat", seats_show_path(show)